version: "3"

services:
  database: # name of the service
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    command: --smallfiles

  api_web:      # name the second service
    build: api  # specify the directory of the dockerfile
    container_name: nodejs
    volumes:
      - ./api:/usr/src/api # copy files in containers
    ports:
      - "3001:3001" # specify port mapping
    environment:
      PORT: 3001
    links:
      - database

  app_web:          # name the firs service
    build: app # specify the directory of the dockerfile
    container_name: reactjs
    volumes:
      - ./app:/usr/src/app # copy files in containers
    ports:
      - "3000:3000" # specify port mapping
